# Import des templates de jobs pré-configurés
include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

stages:
  - build

# Construction d'une image Docker pour les builds OCSIN
build:dev:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-build-base --destination $CI_REGISTRY_IMAGE:build-base-${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}

# Construction d'une image Docker pour l'image finale d'OCSIN
build:alpine:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs: ["build:dev"]
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: "$CI_COMMIT_TAG =~ /v.*$/"
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-alpine --build-arg BUILD_BASE_SHA1=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} --destination $CI_REGISTRY_IMAGE:alpine-${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
