version: "3"
services:
  app:
    image: git.octree.ch:4567/decidim/ocsin
    volumes:
      - node_modules:/app/node_modules
      - ./storage/rails:/code/storage
      - ./storage/uploads:/code/public/uploads
      - ./log:/code/log
    environment:
      - PORT=80
      - RAILS_ENV=production
    env_file: .env
    ports:
      - 80:80

volumes:
  node_modules: {}
