
ARG ALPINE_RUBY_VERSION=2.7.3
ARG BUILD_BASE_SHA1
ARG BUNDLER_VERSION=2.2.22
# Should exists for alpine, see https://unofficial-builds.nodejs.org/download/release/
ARG NODE_VERSION=v16.13.0 
ARG USER=decidim
ARG USER_UID=1000
ARG GROUP=admin
ARG GROUP_UID=1000

########################################################################
# Dependancy layer
########################################################################
FROM git.octree.ch:4567/decidim/ocsin:build-base-${BUILD_BASE_SHA1}  AS dependancy

########################################################################
# Final layer
########################################################################
FROM ruby:${ALPINE_RUBY_VERSION}-alpine
LABEL maintainer="hello@octree.ch"
ARG ALPINE_RUBY_VERSION
ARG BUNDLER_VERSION
ARG USER
ARG USER_UID
ARG GROUP
ARG GROUP_UID

ENV USER=$USER \
    USER_UID=$USER_UID \
    GROUP=$GROUP\
    GROUP_UID=$GROUP_UID \
    RAILS_ENV=production \
    RACK_ENV=production \
    TZ=Europe/Zurich \
    LANG=C.UTF-8 \
    RAILS_SERVE_STATIC_FILES=false \
    BUNDLER_VERSION=$BUNDLER_VERSION \
    RAILS_ROOT=/home/$USER/app

ENV PATH=$PATH:$RAILS_ROOT/bin

WORKDIR $RAILS_ROOT

RUN apk update && \
    apk upgrade && \
    gem update --system && \
    gem install bundler --version "$BUNDLER_VERSION" && \
    apk add --no-cache \
        postgresql-dev \
        tzdata \
        imagemagick \
        bash \
        vim \
        && rm -rf /var/cache/apk/*

# Create system user to run as non-root.
RUN addgroup -S $GROUP -g $GROUP_UID && \
    adduser -S -g '' -u $USER_UID -G $GROUP $USER

VOLUME /home/$USER/app/storage
VOLUME /home/$USER/app/public
VOLUME /home/$USER/app/log

# Copy app & gems
COPY --from=dependancy /usr/local/bundle/ /usr/local/bundle/
COPY --chown=$USER:$GROUP --from=dependancy /home/$USER/app ./

# Add imagemagick policy
RUN mv $RAILS_ROOT/.docker/imagemagick-policy.xml /etc/ImageMagick-7/policy.xml && \
    # Set bundle config again, to have passing bundle check
    bundle config set without 'development test'

# Switch to non-root system user
USER $USER


# Define bash as the default shell
SHELL ["/bin/bash", "-l", "-c"]

ENTRYPOINT [".docker/entrypoint.sh"]

CMD ["bundle", "exec", "rails", "server"]