version: "3"
services:
  app:
    image: git.octree.ch:4567/decidim/ocsin
    volumes:
      - node_modules:/app/node_modules
      - ./storage/rails:/code/storage
      - ./storage/uploads:/code/public/uploads
      - ./storage/styles:/code/app/assets/stylesheets/organizations
      - ./storage/certs:/certs
      - ./log:/code/log
    environment:
      - PORT=443
      - RAILS_ENV=production
    env_file: .env
    ports:
      - 443:443

volumes:
  node_modules: {}
