version: "3"
services:
  app:
    image: decidim
    build: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - pg
      - mailer

  pg:
    image: postgres:11
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=p28ZRFZeitqovv9Puvse
      - POSTGRES_USER=postgres
      - POSTGRES_DB=decidim_quickstart

  mailer:  
    image: tophfr/mailcatcher
    ports:
      - "1025:1025"
      - "1080:80"

volumes:
  node_modules: {}
  pg-data: {}
